In [44]:
import os
import pandas as pd
import numpy as np
from skimage.io import imread
from skimage.transform import resize

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from typing import Tuple

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MaxAbsScaler


from sklearn.neighbors import KNeighborsClassifier

from zipfile import ZipFile


def Gems_load(img_size: Tuple[int, int]):
    gems_class = []
    gems_image = []
    #base_path = '../data/00_038.png'
 

    with ZipFile('../data/raw_data/d17 - gemstones_I.zip', 'r') as zip:
        zip.extractall('../data/preprocessed_data/d17 - gemstones_I')
    
    
    for root, dirs, files in os.walk('../data/preprocessed_data/d17 - gemstones_I/train'):
        path = root.split(os.sep)
        class_name = os.path.basename(root)# (len(path) - 1) * ''#,      
        for file in files:
            image = imread(root + '/' + file, as_gray=True)
                        
            if image.shape != img_size:
                print(image.shape)
                image = resize(image, img_size, anti_aliasing=True)
                print(image.shape)

            gems_image.append(image.ravel())
            gems_class.append(class_name)

    
    image_matrix = np.stack(gems_image)
    del gems_image
    
    le = LabelEncoder()
    le.fit(gems_class)
    gems_class = le.transform(gems_class)
    
    #print(image_matrix.shape)
    #print(gems_class_np.shape)
    
    print(image_matrix)
    print(gems_class)

    return gems_class, image_matrix


traget_gems, gems_images = Gems_load((50,50))



(533, 800)
(50, 50)
(1024, 1024)
(50, 50)
(225, 225)
(50, 50)
(450, 450)
(50, 50)
(372, 453)
(50, 50)
(329, 330)
(50, 50)
(170, 183)
(50, 50)
(368, 368)
(50, 50)
(322, 273)
(50, 50)
(432, 279)
(50, 50)
(157, 145)
(50, 50)
(179, 196)
(50, 50)
(457, 551)
(50, 50)
(336, 336)
(50, 50)
(213, 237)
(50, 50)
(200, 200)
(50, 50)
(465, 465)
(50, 50)
(320, 513)
(50, 50)
(500, 462)
(50, 50)
(491, 522)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(390, 597)
(50, 50)
(280, 280)
(50, 50)
(266, 293)
(50, 50)
(186, 191)
(50, 50)
(178, 161)
(50, 50)
(326, 456)
(50, 50)
(300, 280)
(50, 50)
(200, 200)
(50, 50)
(290, 290)
(50, 50)
(269, 353)
(50, 50)
(206, 213)
(50, 50)
(225, 225)
(50, 50)
(225, 225)
(50, 50)
(225, 225)
(50, 50)
(200, 200)
(50, 50)
(203, 252)
(50, 50)
(290, 290)
(50, 50)
(206, 213)
(50, 50)
(400, 400)
(50, 50)
(234, 244)
(50, 50)
(400, 400)
(50, 50)
(350, 350)
(50, 50)
(400, 400)
(50, 50)
(225, 225)
(50, 50)
(225, 225)
(50, 50)
(258, 280)
(50, 50)
(248, 170)
(50, 50)
(237, 260)
(50, 50

(455, 465)
(50, 50)
(236, 236)
(50, 50)
(483, 483)
(50, 50)
(290, 290)
(50, 50)
(225, 225)
(50, 50)
(400, 400)
(50, 50)
(236, 236)
(50, 50)
(188, 268)
(50, 50)
(463, 463)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(350, 360)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(534, 589)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(400, 400)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(349, 349)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(225, 225)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)


(50, 50)
(401, 401)
(50, 50)
(151, 190)
(50, 50)
(301, 301)
(50, 50)
(401, 401)
(50, 50)
(234, 290)
(50, 50)
(259, 259)
(50, 50)
(401, 401)
(50, 50)
(301, 301)
(50, 50)
(401, 401)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(301, 301)
(50, 50)
(401, 401)
(50, 50)
(300, 300)
(50, 50)
(320, 320)
(50, 50)
(300, 300)
(50, 50)
(234, 236)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(360, 360)
(50, 50)
(300, 300)
(50, 50)
(301, 301)
(50, 50)
(238, 236)
(50, 50)
(260, 260)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(400, 400)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(188, 236)
(50, 50)
(300, 300)
(50, 50)
(280, 280)
(50, 50)
(400, 400)
(50, 50)
(301, 301)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(214, 236)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(250, 250)
(50, 50)
(225, 225)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(224, 224)


(50, 50)
(400, 400)
(50, 50)
(401, 401)
(50, 50)
(300, 300)
(50, 50)
(322, 322)
(50, 50)
(240, 265)
(50, 50)
(395, 395)
(50, 50)
(290, 290)
(50, 50)
(350, 350)
(50, 50)
(425, 425)
(50, 50)
(212, 207)
(50, 50)
(425, 425)
(50, 50)
(425, 425)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(425, 425)
(50, 50)
(320, 320)
(50, 50)
(301, 301)
(50, 50)
(290, 290)
(50, 50)
(300, 300)
(50, 50)
(368, 368)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(400, 400)
(50, 50)
(425, 425)
(50, 50)
(412, 437)
(50, 50)
(290, 290)
(50, 50)
(422, 422)
(50, 50)
(543, 543)
(50, 50)
(425, 425)
(50, 50)
(225, 224)
(50, 50)
(263, 270)
(50, 50)
(300, 300)
(50, 50)
(231, 231)
(50, 50)
(290, 290)
(50, 50)
(300, 300)
(50, 50)
(200, 200)
(50, 50)
(297, 297)
(50, 50)
(225, 225)
(50, 50)
(299, 323)
(50, 50)
(224, 224)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(300, 300)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(225, 225)
(50, 50)
(290, 290)
(50, 50)
(200, 200)


(480, 480)
(50, 50)
(224, 225)
(50, 50)
(295, 372)
(50, 50)
(263, 292)
(50, 50)
(268, 273)
(50, 50)
(437, 437)
(50, 50)
(171, 171)
(50, 50)
(340, 389)
(50, 50)
(185, 200)
(50, 50)
(420, 420)
(50, 50)
(229, 278)
(50, 50)
(350, 378)
(50, 50)
(443, 325)
(50, 50)
(160, 160)
(50, 50)
(323, 373)
(50, 50)
(406, 406)
(50, 50)
(225, 225)
(50, 50)
(156, 198)
(50, 50)
(424, 424)
(50, 50)
(195, 258)
(50, 50)
(183, 191)
(50, 50)
(238, 274)
(50, 50)
(480, 480)
(50, 50)
(400, 400)
(50, 50)
(399, 480)
(50, 50)
(338, 338)
(50, 50)
(225, 225)
(50, 50)
(159, 200)
(50, 50)
(168, 194)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(401, 401)
(50, 50)
(401, 401)
(50, 50)
(290, 290)
(50, 50)
(290, 290)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(290, 290)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)
(401, 401)
(50, 50)
(300, 300)
(50, 50)
(300, 300)
(50, 50)


(50, 50)
(500, 500)
(50, 50)
(395, 395)
(50, 50)
(231, 218)
(50, 50)
(295, 295)
(50, 50)
(452, 452)
(50, 50)
(263, 269)
(50, 50)
(225, 225)
(50, 50)
(250, 250)
(50, 50)
(301, 370)
(50, 50)
(464, 464)
(50, 50)
(400, 400)
(50, 50)
(280, 240)
(50, 50)
(324, 324)
(50, 50)
(395, 395)
(50, 50)
(205, 228)
(50, 50)
(331, 404)
(50, 50)
(460, 460)
(50, 50)
(379, 379)
(50, 50)
(245, 327)
(50, 50)
(290, 290)
(50, 50)
(202, 192)
(50, 50)
(225, 300)
(50, 50)
(248, 305)
(50, 50)
(185, 236)
(50, 50)
(347, 347)
(50, 50)
(328, 245)
(50, 50)
(205, 216)
(50, 50)
(395, 395)
(50, 50)
(250, 250)
(50, 50)
(387, 400)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(290, 290)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(288, 268)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(301, 301)
(50, 50)
(300, 300)
(50, 50)
(301, 301)


(50, 50)
(225, 225)
(50, 50)
(300, 300)
(50, 50)
(401, 401)
(50, 50)
(300, 300)
(50, 50)
(290, 290)
(50, 50)
(301, 301)
(50, 50)
(400, 400)
(50, 50)
(225, 225)
(50, 50)
(330, 380)
(50, 50)
(335, 356)
(50, 50)
(301, 301)
(50, 50)
(401, 401)
(50, 50)
(340, 372)
(50, 50)
(250, 300)
(50, 50)
(401, 401)
(50, 50)
(300, 300)
(50, 50)
(340, 340)
(50, 50)
(201, 226)
(50, 50)
(300, 300)
(50, 50)
(392, 392)
(50, 50)
(290, 290)
(50, 50)
(204, 227)
(50, 50)
(584, 584)
(50, 50)
(194, 226)
(50, 50)
(200, 200)
(50, 50)
(290, 290)
(50, 50)
(180, 180)
(50, 50)
(401, 401)
(50, 50)
(225, 225)
(50, 50)
(290, 290)
(50, 50)
(371, 371)
(50, 50)
(361, 361)
(50, 50)
(300, 300)
(50, 50)
(290, 290)
(50, 50)
(412, 412)
(50, 50)
(354, 354)
(50, 50)
(400, 400)
(50, 50)
(371, 371)
(50, 50)
(420, 420)
(50, 50)
(290, 290)
(50, 50)
(540, 540)
(50, 50)
(449, 329)
(50, 50)
(290, 290)
(50, 50)
(370, 370)
(50, 50)
(377, 377)
(50, 50)
(240, 300)
(50, 50)
(290, 290)
(50, 50)
(225, 225)
(50, 50)
(223, 207)
(50, 50)
(290, 290)


In [8]:


print("Encoding")
le = LabelEncoder()
le.fit(train_target)
train_target = le.transform(train_target)
print("Encoding end")
train_target

Encoding


NameError: name 'train_target' is not defined

In [45]:
print(traget_gems)
print(gems_images)

[70 70 70 ... 45 45 45]
[[0.37978755 0.3796614  0.38098554 ... 0.35688412 0.35295248 0.36145855]
 [0.27403722 0.27523019 0.27754435 ... 0.22301816 0.22229026 0.23670046]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 0.76483155 0.77360006 0.7808024 ]
 [1.         1.         1.         ... 1.         1.         1.        ]]


In [48]:
train_gems, test_gems, train_target, test_target = train_test_split(
            gems_images, traget_gems, test_size=0.2, random_state=71)


In [49]:
print(train_gems)
print(train_target)

[[0.81682445 0.82164651 0.81680945 ... 0.73875305 0.74007119 0.74457878]
 [0.83977682 0.83977682 0.83977684 ... 0.86649331 0.87034531 0.8704959 ]
 [0.99552784 0.99552784 0.99556975 ... 0.99089594 0.99154848 0.99166671]
 ...
 [0.92941176 0.92941176 0.92941176 ... 0.92941176 0.92941176 0.92941176]
 [1.         1.         1.         ... 1.         1.         1.        ]
 [0.95686275 0.95686275 0.95686275 ... 0.95686275 0.95686275 0.95686275]]
[76 56 64 ... 82 81  4]


In [50]:
#train_gems = train_gems.reshape(-1,1)

In [51]:
#reduced_train = r_method.fit_transform(train_gems)
#print(train_gems)
max_abs = MaxAbsScaler().fit(train_target.reshape(1,-1))
#train_gems = max_abs.fit(train_gems.reshape(-1,1))
train_target = max_abs.transform(train_target.reshape(1,-1))


In [52]:
train_gems

array([[0.81682445, 0.82164651, 0.81680945, ..., 0.73875305, 0.74007119,
        0.74457878],
       [0.83977682, 0.83977682, 0.83977684, ..., 0.86649331, 0.87034531,
        0.8704959 ],
       [0.99552784, 0.99552784, 0.99556975, ..., 0.99089594, 0.99154848,
        0.99166671],
       ...,
       [0.92941176, 0.92941176, 0.92941176, ..., 0.92941176, 0.92941176,
        0.92941176],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.95686275, 0.95686275, 0.95686275, ..., 0.95686275, 0.95686275,
        0.95686275]])

In [53]:
print(train_gems.)

#train_target

[[0.81682445 0.82164651 0.81680945 ... 0.73875305 0.74007119 0.74457878]
 [0.83977682 0.83977682 0.83977684 ... 0.86649331 0.87034531 0.8704959 ]
 [0.99552784 0.99552784 0.99556975 ... 0.99089594 0.99154848 0.99166671]
 ...
 [0.92941176 0.92941176 0.92941176 ... 0.92941176 0.92941176 0.92941176]
 [1.         1.         1.         ... 1.         1.         1.        ]
 [0.95686275 0.95686275 0.95686275 ... 0.95686275 0.95686275 0.95686275]]


In [59]:
print(train_target)

[[1. 1. 1. ... 1. 1. 1.]]


In [61]:
clf = KNeighborsClassifier(3)
clf.fit(train_gems, train_target[0])
print(f'result: {clf.score(test_gems, test_target)}')

result: 0.012237762237762238
